# Etape 1 : image de base Node.js
FROM node:20

# Etape 2 : creer le dossier de l'application
WORKDIR /app

# Etape 3 : copier package.json et package-lock.json
COPY package*.json ./

# Etape 4 : installer les dependances
RUN npm install

# Etape 5 : copier tout le code backend
COPY . .

# Etape 6 : exposer le port 3000
EXPOSE 3000

# Etape 7 : lancer serveur avec node (pas nodemon)
CMD ["node", "server.js"]
