[mini_chat_servers]
# METTRE LA NOUVELLE IP DE L'INSTANCE EC2 ICI
# Exemple : NOUVELLE_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/mini-chat-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'