name: CI/CD Mini-Chat

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # === JOB 1: TESTS ET VÉRIFICATION ===
  tests:
    name: Tests et Lint
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Installation des dépendances
        working-directory: ./backend
        run: npm ci

      - name: Exécution du linter
        working-directory: ./backend
        run: npm run lint || echo "Pas de script de linter"

      - name: Exécution des tests
        working-directory: ./backend
        run: npm test || echo "Pas de tests pour le moment"


  # === JOB 2 : CONSTRUCTION DOCKER ===
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test des conteneurs Docker
        run: |
          cd docker
          cp .env.example .env
          docker compose up --build backend db -d
          sleep 20
          docker ps
          curl -f http://localhost:3000 || exit 1
          docker compose down


  deploy:
    name: validation et deploiement par terraform
    runs-on: ubuntu-latest
    needs: [tests, build]
    steps: 
      - name: recuperation du code
        uses: actions/checkout@v4
      
      - name: installer terraform
        uses:  hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5'
         
      - name: inistialisation de terraform
        run: |
          cd terraform
          terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: validation de fichier installer 
        run: |
          cd terraform
          terraform validate
      
      - name: check 
        run: |
          cd terraform
          terraform fmt -check
      
      - name : terraform apply
        run: |
          cd terraform
          cp terraform.tfvars.example ci_cd.tf
          terraform apply -auto-approve -var-file="terraform.tfvars.example"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

