name: CI/CD Mini-Chat

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # === JOB 1: BUILD AND PUSH BACKEND IMAGE ===
  build-and-push:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mini-chat-backend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f backend/dockerfile.backend ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  # === JOB 2: TESTS ET VÉRIFICATION ===
  tests:
    name: Tests et Lint
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Installation des dépendances
        working-directory: ./backend
        run: npm ci

      - name: Exécution du linter
        working-directory: ./backend
        run: npm run lint || echo "Pas de script de linter"

      - name: Exécution des tests
        working-directory: ./backend
        run: npm test || echo "Pas de tests pour le moment"


  # === JOB 2 : CONSTRUCTION DOCKER ===
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test des conteneurs Docker
        run: |
          cd docker
          cp .env.example .env
          docker compose up --build backend db -d
          sleep 20
          docker ps
          curl -f http://localhost:3000 || exit 1
          docker compose down


  deploy:
    name: validation et deploiement par terraform
    runs-on: ubuntu-latest
    needs: [tests, build-and-push]
    steps: 
      - name: recuperation du code
        uses: actions/checkout@v4
      
      - name: installer terraform
        uses:  hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5'
         
      - name: inistialisation de terraform
        run: |
          cd terraform
          terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
            
      - name: validation de fichier installer 
        run: |
          cd terraform
          terraform validate
      
      - name: check 
        run: |
          cd terraform
          terraform fmt -check

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name : terraform apply
        run: |
          cd terraform
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_password: ${{ secrets.db_password }}
          TF_VAR_key_name: ${{ secrets.key_name }}

